import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Patito Vendedor',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <header className="bg-gray-800 text-white p-4">
          <nav className="container mx-auto flex justify-between items-center">
            <a href="/" className="font-bold text-xl">
              Patito Vendedor
            </a>
            <ul className="flex space-x-4">
                <li><a href="/crear-cuenta">Crear cuenta</a></li>
                <li><a href="/dashboard">Dashboard</a></li>
                <li><a href="/perfil">Perfil</a></li>
                <li><a href="/login">Iniciar sesión</a></li>
            </ul>
          </nav>
        </header>

        <main className="container mx-auto p-4">
            {children}
        </main>
      </body>
    </html>
  );
}